default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: Perento16
  host: localhost

development:
  <<: *default
  database: Blog-App

test:
  <<: *default
  database: Blog-App

production:
  <<: *default
  database: Blog-App
